#! /bin/sh
# chkconfig: 2345 95 65
# Description: Startup script for transcode on CentOS. Place in /etc/init.d and
# run 'update-rc.d -f transcode defaults', or use the appropriate command on your
# distro. For CentOS/Redhat run: 'chkconfig --add transcode'

### BEGIN INIT INFO
# Provides:          transcode
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the transcode server
# Description:       starts transcode using start-stop-daemon
### END INIT INFO

# Author:   huihoo
# website:  http://www.dnion.com


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=transcode
FFMPEG_BIN=ffmpeg
TRANSCODE_BIN=/home/swift/transcode/transcode_server.py
TRANSCODE_STOP=/home/swift/transcode/stop.py
CONFIGFILE=/home/swift/transcode/$NAME.cfg
PIDFILE=/home/swift/transcode/logs/$NAME.pid

case "$1" in
    start)
        echo -n "Starting $NAME... "

        python $TRANSCODE_BIN -c $CONFIGFILE

        if [ "$?" != 0 ] ; then
            echo " failed"
            exit 1
        else
            echo " done"
        fi
        ;;

    stop)
        echo -n "Stoping $NAME... "

        python $TRANSCODE_STOP

        if [ "$?" != 0 ] ; then
            echo " stop failed."
            exit 1
        else
            echo " done"
        fi
        
        ffmpeg_pids = $(pgrep -f "$FFMPEG_BIN")
        if [ -n $ffmpeg_pids ] ; then
            echo "kill ffmpeg process: $ffmpeg_pids"
            pkill $FFMPEG_BIN
        fi

        ;;

    status)
        if pgrep -f "${TRANSCODE_BIN}" 2>/dev/null 1>&2; then
            PID=$(cat "${PIDFILE}")
            echo "$NAME (pid $PID) is running..."
        else
            echo "$NAME is stopped"
            exit 0
        fi
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;

esac